# -*- cuding: utf-8 -*-
import random
from .models import db, Emails
from . import app


random.seed()


def setPorts():
    dataforbaseisDanger = [
        {"theme": "Требуется немедленное действие: Проверьте свою учетную запись сейчас",
        "from_label": "support@popularsocia1media.com",
        "to_label": "мне",
        "email_body": "Уважаемый пользователь, мы заметили подозрительную активность на вашем аккаунте. Пожалуйста, немедленно проверьте свою учетную запись, чтобы избежать приостановки. Нажмите здесь, чтобы проверить: https:\\\\popularsocia1media.com\\kjdaskjhd Не игнорируйте это критическое предупреждение.",
        "attach": "нет",
        "isDanger": True,
        "isSpam": False},
        {"theme": "Вам не доставлена посылка",
        "from_label": "no-reply@globalcourierservicexy.com",
        "to_label": "мне",
        "email_body": "Мы пытались доставить вашу посылку сегодня, но не смогли с вами связаться. Пожалуйста, скачайте прилагаемую форму, заполните ее и отправьте обратно, чтобы перенести доставку на удобное для вас время.",
        "attach": "form.pdf.exe",
        "isDanger": True,
        "isSpam": False},
        {"theme": "Получите бесплатный доступ к эксклюзивному программному обеспечению прямо сейчас!",
        "from_label": "promotions@softwarehub.com",
        "to_label": "мне",
        "email_body": "Поздравляем! Вы были выбраны для получения бесплатного пожизненного доступа к нашему эксклюзивному программному комплексу. Скачайте приложенный файл, чтобы воспользоваться подарком прямо сейчас. Торопитесь, срок действия предложения истекает!",
        "attach": "GoodProgram.zip",
        "isDanger": True,
        "isSpam": False},
        {"theme": "Срочно: Вам положен налоговый вычет!",
        "from_label": "info@nalog.ru.biz",
        "to_label": "мне",
        "email_body": "Добрый день, налоговая служба РФ соблюдая принципы равноправия и служения закону и гражданам РФ, проведя внеочередную проверку по налогам выявила переплату по налогам и сборам по вашему персональному счету. Пожалуйста, перейдите по этой ссылке, чтобы предоставить свои учетные данные и получить возмещение в размере 30 т.р.: https:\\\\nalog.ru.biz\\tax_deduction",
        "attach": "нет",
        "isDanger": True,
        "isSpam": False},
        {"theme": "Последнее предупреждение: Ваша учетная запись электронной почты будет деактивирована!",
        "from_label": "admin@mai1.su",
        "to_label": "мне",
        "email_body": "Ваша учетная запись электронной почты была помечена для деактивации в связи с неактивностью. Чтобы сохранить вашу учетную запись активной, загрузите прилагаемую форму соответствия, заполните ее и отправьте в течение 24 часов.",
        "attach": "FormActivation.zip",
        "isDanger": True,
        "isSpam": False},
        {"theme": "Для вас доступен VIP доступ. Поздравляем!",
        "from_label": "events@hjhdbrand.ru",
        "to_label": "мне",
        "email_body": "Спасибо что Вы есть. Вы были специально отобраны для участия в нашем эксклюзивном VIP-мероприятии. Количество мест ограничено, поэтому обеспечьте себе место прямо сейчас, перейдя по этой ссылке: https:\\\\hjhdbrand.ru\\join. Мы с нетерпением ждем вас!",
        "attach": "нет",
        "isDanger": True,
        "isSpam":False},
        {"theme": "Вход в систему из необычной локации",
        "from_label": "security@sber.bunk.ru",
        "to_label": "мне",
        "email_body": "Мы обнаружили необычную попытку входа в вашу учетную запись с нового устройства. Это были вы? Просмотрите попытку входа и примите меры, перейдя по этой ссылке: http:\\\\sber.bunk.ru\\hjgjhgsyu-12sdaqa-asas.",
        "attach": "нет",
        "isDanger": True,
        "isSpam": False},
        {"theme": "Разблокируйте доступ к бесплатному онлайн-курсу прямо сейчас!",
        "from_label": "newsletter@skilbuks.ru",
        "to_label": "мне",
        "email_body": "Как ценный подписчик, вы получаете эксклюзивный бесплатный доступ к нашему новому онлайн-курсу. Это предложение ограничено! Поторопитесь! Загрузите материалы нашего новогу курса, чтобы начать обучение уже сегодня: https:\\\\skilbuks.ru\\new_course_sxsd6612b",
        "attach": "нет",
        "isDanger": True,
        "isSpam": False},
        {"theme": "Оплата вашей покупки прошла успешно, нужно подтвердить получение",
        "from_label": "billing@wilbderres.ru",
        "to_label": "мне",
        "email_body": "Благодарим вас за недавнюю покупку. Чтобы завершить заказ олплаченный с вашей карты, пожалуйста, подтвердите адрес доставки, нажав здесь: https:\\\\wilbderres.ru\\adress_to_delivery Спасибо что совершаете покупки в нашем магазине.",
        "attach": "нет",
        "isDanger": True,
        "isSpam": False},
        {"theme": "Обновить информацию о платежах",
        "from_label": "support@steempower.com",
        "to_label": "мне",
        "email_body": "У нас возникла проблема с вашим текущим способом оплаты. Пожалуйста, обновите платежную информацию, чтобы продолжить пользоваться нашим игровым сервисом. Перейдите по ссылке для обновления платежных роеквизитов: https:\\\\steempower.com\\billing.",
        "attach": "нет",
        "isDanger": True,
        "isSpam": False}
    ]
    dataforbaseisDanger = [
        {"theme": "Преобразите свое тело всего за 30 дней!",
        "from_label": "healthsolutions@wellnessworld.com",
        "to_label": "alexey88@mail.ru, maria2002@mail.ru, ivan_ivanov@mail.ru, olga.petrova@mail.ru, sergey1990@mail.ru, ekaterina_s@mail.ru",
        "email_body": "Откройте для себя секрет быстрой потери веса без тренажерного зала! Тысячи людей достигли тела своей мечты благодаря этому простому приему. Переходите по ссылке, чтобы раскрыть секрет прямо сейчас: https:\\\\wellnessworld.com.",
        "attach": "нет",
        "isDanger": False,
        "isSpam": True},
        {"theme": "Получите мгновенное одобрение кредита сегодня - одобрение за 5 минут по номеру телефона!",
        "from_label": "quickloans@financefast.ru",
        "to_label": "dmitry.d@mail.ru, natalia88@mail.ru, vladimir_k@mail.ru, irina_smirnova@mail.ru, pavel.pavlov@mail.ru, anna_k@mail.ru",
        "email_body": "Вам срочно нужны наличные? Получите мгновенное одобрение кредита уже сегодня без проверки. Получите средства прямо сейчас: https:\\\\financefast.ru. Это быстро и просто!",
        "attach": "нет",
        "isDanger": False,
        "isSpam": True},
        {"theme":,
        "from_label":,
        "to_label":,
        "email_body":,
        "attach": "нет",
        "isDanger": False,
        "isSpam": True},
        {"theme":,
        "from_label":,
        "to_label":,
        "email_body":,
        "attach": "нет",
        "isDanger": False,
        "isSpam": True},
        {"theme":,
        "from_label":,
        "to_label":,
        "email_body":,
        "attach": "нет",
        "isDanger": False,
        "isSpam": True},
    ]
    with app.app_context():
        if Emails.query.count() == 0:
            for data in dataforbaseisDanger:
                question = Emails(**data)
                db.session.add(question)
            db.session.commit()

setPorts()
