FROM tiangolo/uwsgi-nginx-flask:python3.11

RUN apt-get update && \
apt-get install -y cron default-mysql-client nano netcat-traditional && \
rm -rf /var/lib/apt/lists/*

COPY ./flask_app /app

COPY ./flask_app/app/static /app/static
COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY requirements.txt /var/www/requirements.txt
RUN pip install -r /var/www/requirements.txt

ENV TZ Europe/Moscow

COPY ./crontab/cron-script-delete-from-users.sh /usr/local/bin/cron-script-delete-from-users.sh
RUN chmod +x /usr/local/bin/cron-script-delete-from-users.sh
COPY ./crontab/cron-script-delete-from-session.sh /usr/local/bin/cron-script-delete-from-session.sh
RUN chmod +x /usr/local/bin/cron-script-delete-from-session.sh
COPY ./crontab/delete_data /etc/cron.d
RUN chmod 0644 /etc/cron.d/delete_data

COPY wait-for-db.sh /usr/local/bin/wait-for-db.sh
RUN chmod +x /usr/local/bin/wait-for-db.sh


