version: '3.3'
services:
  db_lesson212:
    image: mysql:latest
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: lesson212
      MYSQL_DATABASE: lesson212
      MYSQL_USER: lesson212
      MYSQL_PASSWORD: lesson212
  lesson212:
    build:
      context: .
      dockerfile: Dockerfile_tiangolo
    ports:
      - "8080:80"
    environment:
      DB_HOST: db_lesson212
      DB_PORT: 3306
      DB_ROOT_PASSWORD: lesson212
      DB_DATABASE: lesson212
      DB_USER: lesson212
      DB_PASSWORD: lesson212
      FLASK_ENV: production
    command: ["/usr/local/bin/wait-for-db.sh"]
volumes:
  db_data:
