FROM tiangolo/uwsgi-nginx-flask:python3.11

RUN apt-get update && \
apt-get install -y default-mysql-client nano netcat && \
rm -rf /var/lib/apt/lists/*

COPY ./flask_app /app

COPY requirements.txt /var/www/requirements.txt
RUN pip install -r /var/www/requirements.txt

COPY wait-for-db.sh /usr/local/bin/wait-for-db.sh
RUN chmod +x /usr/local/bin/wait-for-db.sh


