version: '3.3'
services:
  db_lesson132:
    image: mysql:latest
    restart: always
    ports:
      - "33062:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: lesson132
      MYSQL_DATABASE: lesson132
      MYSQL_USER: lesson132
      MYSQL_PASSWORD: lesson132
  lesson132:
    build:
      context: .
      dockerfile: Dockerfile_tiangolo
    ports:
      - "8082:80"
volumes:
  db_data:
