FROM tiangolo/uwsgi-nginx-flask:python3.11

RUN apt-get update && apt-get install -y cron && apt-get install -y default-mysql-client
COPY ./flask_app /app

COPY ./crontab /etc/cron.d/crontab

COPY requirements.txt /var/www/requirements.txt
RUN pip install -r /var/www/requirements.txt

COPY ./crontab /etc/cron.d
RUN chmod 0644 /etc/cron.d/delete_data
RUN crontab /etc/cron.d/delete_data

ENTRYPOINT service start cron