version: '3.3'
services:
  cyberbingo:
    image: httpd:latest
    volumes:
      - ./www:/usr/local/apache2/htdocs/
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - 8084:80
