version: '3.3'
services:
  db_test_uts:
    image: mysql:latest
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: lesson13134
      MYSQL_DATABASE: lesson13134
      MYSQL_USER: lesson13134
      MYSQL_PASSWORD: lesson13134
  test_uts:
    build:
      context: .
      dockerfile: Dockerfile_tiangolo
    ports:
      - "8080:80"
    environment:
      DB_HOST: db_lesson13134
      DB_PORT: 3306
      DB_ROOT_PASSWORD: lesson13134
      DB_DATABASE: lesson13134
      DB_USER: lesson13134
      DB_PASSWORD: lesson13134
      FLASK_DEBUG: production
      TOKEN_API_KEY: "token_api_"
      SECRET_KEY: "_secret_"
    command: ["/usr/local/bin/wait-for-db.sh"]
volumes:
  db_data:
